### ISSUE TITLE
Plugin support for 3.3

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/pkp-adminNotificationManager#10]
To support 3.3 we will need:

- To convert the locale .xml to .po
- Update the README to better describe the plugin function and update the version requirement
- Align the method signatures (and documentation) to the signature from the class which it extends.

**Comment by trp89** [comment]
- .xml to .po conversion:  '7df148d'
- README Update:  'db6e513'
- Aligning method signatures:  #11
